CusApp/urls.py
from django.urls import path, re_path
from CusApp import views


app_name = "CusApp"

urlpatterns = [
    path("AddCustomer/", views.AddCustomer.as_view(), name = "AddCustomer"),
    path("Logout/", views.Logout_View.as_view(), name = "Logout"),
    path("Customer/", views.index.as_view(), name = "Customer"),
    path('', views.index.as_view(), name="index"),
    path("Search/", views.Search_View.as_view(), name = "Search"),
    path("login/", views.Login_View.as_view(), name = "login"),
    path("signup/", views.Sigup_View.as_view(), name= "signup"),
    path(r'^(?P<pk>\d+)/itemdelete/$', views.DeleteItem.as_view(), name = 'DeleteItem' ),
    path(r'^(?P<pk>\d+)/Profile/$', views.Customer_View.as_view(), name = 'CustomerView' ),
    path("submitted/", views.Submitted_View.as_view(), name = "submitted"),
    re_path('cart/', views.Cart_View.as_view(), name = 'cart' ),




]

Customers/urls.py
from django.contrib import admin
from django.urls import path, re_path
from CusApp import views,urls
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index.as_view(), name = "index"),
    path("CusApp/", include("CusApp.urls")),
]

templates/CusAppTemp/Cart.html
{{user}}

<br><br>



{%for i in cart%}


{{i.url}}  <br>
{{i.color}} <br>
{{i.weight}} <br> <br>
    <form action="{% url "CusApp:DeleteItem" i.id %}" method="post">
    {%csrf_token%}
    <input type="submit"  value="Delete">
    </form>


{%endfor%}


<form action="{% url "CusApp:submitted" %}" method="post">
{%csrf_token%}
<input type="submit" value="Submit Order">
</form>

templates/CusAppTemp/CustomerAdd.html
<h2> Add Customer </h2>
<form action = "" method = "POST">
    {%csrf_token%}
    {{form.as_p}}

    <input type = "submit" value = "Submit">

</form>

templates/CusAppTemp/Customerinfo.html
{{newcustomer.Customer_Name}}
{{newcustomer.total}}

templates/CusAppTemp/Summary.html
<p>Order Summary</p>

{%for i in user%}
{{i.url}}<br>
{{i.color}}<br>
{{i.weight}}<br>
{%endfor%}

templates/CusAppTemp/index.html
<!DOCTYPE html>
<h2><em> Kanarya  </em> </h2>
{%if user.is_authenticated%}
{%if perms.is_superuser%}
<a href="{% url 'CusApp:AddCustomer' %}">Click here to add a cusomter</a><br>


<a href="{% url 'CusApp:Search' %}">Find a customer</a><br>


{%endif%}
{%endif%}
{%if error%}
{{error}}
{%endif%}
{%if not user.is_authenticated%}
<a href="{% url "CusApp:login" %}">Login</a>
<br><br><br><br>
<a href="{% url "CusApp:signup" %}"> Signup </a>
{%else%}


<a href="{% url "CusApp:CustomerView" user.id %}">Profile</a><br>
<a href="{% url "CusApp:cart"  %}">Cart</a><br>
<br><br>

<form method="POST">
    {%csrf_token%}
    {%if added is True%}
    <p>Your item has been added successfuly</p>
    {%endif%}
{{form}}

<input type="submit" value="Add to cart">

</form>
<br><br><br><br><br><br><br><br><br>
<br><br><br><br><br><br><br><br><br>



<a href="{% url "CusApp:Logout" %}">logout</a>
{%endif%}

templates/CusAppTemp/login.html
<form method = "POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type = "submit" value = "Login">
</form>

templates/CusAppTemp/registered.html
{{registered}}
<p>Please login here</p> <a href="{% url "CusApp:login" %}"> Login </a>

templates/CusAppTemp/search.html
<h2> Search for a customer </h2>


{%if id%}
<a href="{% url 'CusApp:CustomerView' id%}">{{name}}</a>
{%endif%}
{{error}}

<form action = "" method = "POST">
    {%csrf_token%}
    {{search.as_p}}

    <input type = "submit" value = "Search">

</form>

<br>

templates/CusAppTemp/signup.html
{{registered}}
<form  method="POST">
    {%csrf_token%}
    {{form.as_p}}

    <input type="submit" value="Signup">
</form>